# Generated by Django 3.2.6 on 2021-08-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
            ],
        ),
    ]
